In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


import seaborn as sns
%matplotlib inline

In [50]:
data=pd.read_csv("Football_Dataset_2015_2025.csv")
data.head()
data["Competition"].unique()

array(['La Liga', 'Bundesliga', 'Serie A', 'Premier League',
       'UEFA Champions League'], dtype=object)

In [51]:
data.columns

Index(['Date', 'Competition', 'Home Team', 'Away Team', 'Home Goals',
       'Away Goals', 'Possession % (Home)', 'Possession % (Away)',
       'Shots (Home)', 'Shots (Away)', 'Corners (Home)', 'Corners (Away)',
       'Fouls (Home)', 'Fouls (Away)', 'Winner', 'Year'],
      dtype='object')

In [52]:
data.isnull().sum()

Date                   0
Competition            0
Home Team              0
Away Team              0
Home Goals             0
Away Goals             0
Possession % (Home)    0
Possession % (Away)    0
Shots (Home)           0
Shots (Away)           0
Corners (Home)         0
Corners (Away)         0
Fouls (Home)           0
Fouls (Away)           0
Winner                 0
Year                   0
dtype: int64

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
data=data.drop(["Date"],axis=1)

In [55]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [56]:
labels_Cols=["Competition","Home Team","Away Team","Winner"]
le=LabelEncoder()

In [57]:
for col in labels_Cols:
    data[col]=le.fit_transform(data[col])

In [58]:
data.head()

,Competition,Home Team,Away Team,Home Goals,Away Goals,Possession % (Home),Possession % (Away),Shots (Home),Shots (Away),Corners (Home),Corners (Away),Fouls (Home),Fouls (Away),Winner,Year
0,1,2,0,3,1,44,52,15,20,7,2,12,15,0,2021
1,1,2,3,0,5,52,42,23,19,4,10,13,7,0,2015
2,1,7,3,2,5,55,58,18,16,5,9,7,10,2,2016
3,0,3,8,5,1,63,40,8,12,2,3,15,8,0,2017
4,0,2,6,0,1,41,57,9,12,4,7,11,9,0,2015

In [59]:
data["Competition"].unique()

array([1, 0, 3, 2, 4])

In [60]:
X=data.drop(["Winner","Year"],axis=1)
y=data["Winner"]

In [61]:
X

,Competition,Home Team,Away Team,Home Goals,Away Goals,Possession % (Home),Possession % (Away),Shots (Home),Shots (Away),Corners (Home),Corners (Away),Fouls (Home),Fouls (Away)
0,1,2,0,3,1,44,52,15,20,7,2,12,15
1,1,2,3,0,5,52,42,23,19,4,10,13,7
2,1,7,3,2,5,55,58,18,16,5,9,7,10
3,0,3,8,5,1,63,40,8,12,2,3,15,8
4,0,2,6,0,1,41,57,9,12,4,7,11,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2,5,9,2,2,67,55,10,16,7,6,9,12
2996,1,5,6,0,5,70,56,16,25,3,9,8,6
2997,2,3,9,5,2,61,43,22,6,9,3,15,5
2998,4,4,7,3,2,42,37,7,13,5,7,10,6
2999,0,3,2,1,2,40,46,20,13,10,3,12,6

In [62]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [63]:
num_cols = ['Home Goals', 'Away Goals', 'Possession % (Home)', 'Possession % (Away)', 
            'Shots (Home)', 'Shots (Away)', 'Corners (Home)', 'Corners (Away)', 'Fouls (Home)', 'Fouls (Away)']

In [64]:
scaler=StandardScaler()

In [65]:
X_train[num_cols]=scaler.fit_transform(X_train[num_cols])

In [66]:
X_test[num_cols]=scaler.transform(X_test[num_cols])

In [67]:
from sklearn.linear_model import LogisticRegression

In [68]:
model=LogisticRegression(max_iter=200, multi_class="multinomial", solver="lbfgs")

In [69]:
model.fit(X_train,y_train)

c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(max_iter=200, multi_class='multinomial')

In [70]:
y_pred=model.predict(X_test)

In [71]:
y.unique()

array([0, 2, 1])

In [72]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [73]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.3416666666666667

Classification Report:
               precision    recall  f1-score   support

           0       0.37      0.38      0.38       219
           1       0.32      0.29      0.31       190
           2       0.32      0.34      0.33       191

    accuracy                           0.34       600
   macro avg       0.34      0.34      0.34       600
weighted avg       0.34      0.34      0.34       600


Confusion Matrix:
 [[84 56 79]
 [77 56 57]
 [65 61 65]]