In [ ]:
#1.feature engineering
#2.train test split
#3.bow,word2vec
#4.train ml algorithms

In [ ]:
#load the dataset
import pandas as pd

In [ ]:
data=pd.read_csv("data.csv")

In [ ]:
data

In [ ]:
data=data[["reviewText",'rating']]
data.head()

In [ ]:
data.shape

In [ ]:
data.isnull().sum()

In [ ]:
data["rating"].unique

In [ ]:
data["rating"].value_counts()

In [ ]:
#preprocessing and cleaning

In [ ]:
data["rating"]=data['rating'].apply(lambda x:0 if x<3 else 1)

In [ ]:
data["rating"].unique()

In [ ]:
#1.lower all the cases
data["reviewText"]=data["reviewText"].str.lower()

In [ ]:
data.head()

In [ ]:
#removing speacial characters

In [ ]:
import re
data["reviewText"]=data["reviewText"].apply(lambda x:re.sub('[^a-zA-z0-9]+',' ',x))

In [ ]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')  # download the stopwords dataset

In [ ]:
from bs4 import BeautifulSoup
!pip install lxml

In [ ]:
data['reviewText']=data['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
data['reviewText'] = data['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())

## Remove any additional spaces
data['reviewText']=data['reviewText'].apply(lambda x: " ".join(x.split()))

In [ ]:
data.head( )

                                          reviewText  rating
0  jace rankin may be short but he s nothing to m...       1
1  great short read i didn t want to put it down ...       1
2  i ll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [93]:
#lematizer
from nltk.stem import WordNetLemmatizer

In [94]:
lematizer=WordNetLemmatizer()

In [95]:
def lematize_words(text):
    return " ".join([lematizer.lemmatize(word) for word in text.split()])

In [96]:
data["reviewText"]=data["reviewText"].apply(lambda x:lematize_words(x))

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_14040\1447593968.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["reviewText"]=data["reviewText"].apply(lambda x:lematize_words(x))

In [97]:
data.head()

                                          reviewText  rating
0  jace rankin may be short but he s nothing to m...       1
1  great short read i didn t want to put it down ...       1
2  i ll start by saying this is the first of four...       1
3  aggie is angela lansbury who carry pocketbook ...       1
4  i did not expect this type of book to be in li...       1

In [98]:
## Train Test Split
from sklearn.model_selection import train_test_split

In [99]:
X_train,X_test,y_train,y_test=train_test_split(data['reviewText'],data['rating'],
                                              test_size=0.20)